export type PartnerCategoryId =
  | "furniture"
  | "bath"
  | "office"
  | "lighting"
  | "outdoor"
  | "textiles"
  | "kitchen"
  | "accessories";

export type Partner = {
  name: string;
  slug: string;
  category: PartnerCategoryId;
  categoryLabel: string;
  /** White SVG logo when available. Prefer over image. */
  logo?: string;
  /** White raster mark (processed PNG) when no SVG exists. */
  image?: string;
  /** Official brand site when known. Omit rather than invent. */
  url?: string;
};

export type PartnerCategory = {
  id: PartnerCategoryId;
  label: string;
  line: string;
};

export const partnerCategories: PartnerCategory[] = [
  {
    id: "furniture",
    label: "Furniture",
    line: "Seating, tables, and case goods specified house by house.",
  },
  {
    id: "bath",
    label: "Bath & wellness",
    line: "Wellness rooms specified down to the tap and the stone.",
  },
  {
    id: "office",
    label: "Office",
    line: "Work and reception spaces that still feel like a home.",
  },
  {
    id: "lighting",
    label: "Lighting",
    line: "Layered light, from the first lamp to the last evening.",
  },
  {
    id: "outdoor",
    label: "Outdoor",
    line: "Terraces and gardens specified with the same care as the rooms inside.",
  },
  {
    id: "textiles",
    label: "Textiles & wallcovering",
    line: "Cloth, wallcovering, and the quiet of a finished room.",
  },
  {
    id: "kitchen",
    label: "Kitchen",
    line: "Joinery and kitchens built to the brief, not a catalogue page.",
  },
  {
    id: "accessories",
    label: "Accessories",
    line: "Objects that complete a room without shouting.",
  },
];

export const partners: Partner[] = [
  {
    name: "Gallotti & Radice",
    slug: "gallotti-radice",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/gallotti-radice.svg",
    url: "https://www.gallottiradice.it",
  },
  {
    name: "Giorgetti",
    slug: "giorgetti",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/giorgetti.svg",
    image: "/media/partners/marks/giorgetti.png",
    url: "https://www.giorgetti.eu",
  },
  {
    name: "GUBI",
    slug: "gubi",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/gubi.svg",
    image: "/media/partners/marks/gubi.png",
    url: "https://www.gubi.com",
  },
  {
    name: "Tacchini",
    slug: "tacchini",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/tacchini.svg",
    image: "/media/partners/marks/tacchini.png",
    url: "https://www.tacchini.it",
  },
  {
    name: "Henge",
    slug: "henge",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/henge.svg",
    image: "/media/partners/marks/henge.png",
    url: "https://www.henge07.com",
  },
  {
    name: "Gervasoni",
    slug: "gervasoni",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/gervasoni.svg",
    image: "/media/partners/marks/gervasoni.png",
    url: "https://www.gervasoni1882.com",
  },
  {
    name: "Acerbis",
    slug: "acerbis",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/acerbis.png",
    url: "https://www.acerbisdesign.com",
  },
  {
    name: "Moroso",
    slug: "moroso-furniture",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/moroso.svg",
    url: "https://www.moroso.it",
  },
  {
    name: "Poltrona Frau",
    slug: "poltrona-frau",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/poltrona-frau.png",
    url: "https://www.poltronafrau.com",
  },
  {
    name: "Zeitraum",
    slug: "zeitraum",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/zeitraum.png",
    url: "https://www.zeitraum-moebel.de",
  },
  {
    name: "Arketipo",
    slug: "arketipo",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/arketipo.png",
    url: "https://www.arketipo.com",
  },
  {
    name: "Vitra",
    slug: "vitra",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/vitra.svg",
    url: "https://www.vitra.com",
  },
  {
    name: "Living Divani",
    slug: "living-divani",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/living-divani.svg",
    url: "https://www.livingdivani.it",
  },
  {
    name: "Zanotta",
    slug: "zanotta",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/zanotta.png",
    url: "https://www.zanotta.com",
  },
  {
    name: "Cassina",
    slug: "cassina",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/cassina.svg",
    url: "https://www.cassina.com",
  },
  {
    name: "Cappellini",
    slug: "cappellini",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/cappellini.svg",
    url: "https://www.cappellini.com",
  },
  {
    name: "Fritz Hansen",
    slug: "fritz-hansen",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/fritz-hansen.svg",
    url: "https://www.fritzhansen.com",
  },
  {
    name: "Casadesus",
    slug: "casadesus",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/casadesus.png",
  },
  {
    name: "Baxter",
    slug: "baxter",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/baxter.svg",
    image: "/media/partners/marks/baxter.png",
    url: "https://www.baxter.it",
  },
  {
    name: "Hans Hansen",
    slug: "hans-hansen",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/hans-hansen.png",
  },
  {
    name: "Longhi",
    slug: "longhi",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/longhi.png",
    url: "https://www.longhi.it",
  },
  {
    name: "Busnelli",
    slug: "busnelli",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/busnelli.png",
    url: "https://www.busnelli.it",
  },
  {
    name: "Hamilton Conte",
    slug: "hamilton-conte",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/hamilton-conte.png",
    url: "https://www.hamiltonconte.com",
  },
  {
    name: "Brabbu",
    slug: "brabbu",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/brabbu.png",
    url: "https://www.brabbu.com",
  },
  {
    name: "Guadarte",
    slug: "guadarte",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/guadarte.png",
    url: "https://www.guadarte.com",
  },
  {
    name: "Boca Do Lobo",
    slug: "boca-do-lobo",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/boca-do-lobo.png",
    url: "https://www.bocadolobo.com",
  },
  {
    name: "Modesto Navarro",
    slug: "modesto-navarro",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/modesto-navarro.png",
  },
  {
    name: "Andrew Martin",
    slug: "andrew-martin",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/andrew-martin.png",
    url: "https://www.andrewmartin.co.uk",
  },
  {
    name: "Meridiani",
    slug: "meridiani",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/meridiani.svg",
    image: "/media/partners/marks/meridiani.png",
    url: "https://www.meridiani.it",
  },
  {
    name: "Classicon",
    slug: "classicon",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/classicon.svg",
    image: "/media/partners/marks/classicon.png",
    url: "https://www.classicon.com",
  },
  {
    name: "Missuraemme",
    slug: "missuraemme",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/missuraemme.svg",
    url: "https://www.misuraemme.it",
  },
  {
    name: "Cattelan Italia",
    slug: "cattelan-italia",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/cattelan-italia.png",
    url: "https://www.cattelanitalia.com",
  },
  {
    name: "Cantori",
    slug: "cantori",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/cantori.png",
    url: "https://www.cantoriitalia.com",
  },
  {
    name: "Eric Kuster",
    slug: "eric-kuster",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/eric-kuster.png",
    url: "https://www.erickuster.com",
  },
  {
    name: "Ditre",
    slug: "ditre",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/ditre.svg",
    url: "https://www.ditreitalia.com",
  },
  {
    name: "Gandia Blasco",
    slug: "gandia-blasco",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/gandia-blasco.png",
    url: "https://www.gandiablasco.com",
  },
  {
    name: "Marac",
    slug: "marac",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/marac.png",
    url: "https://www.marac.it",
  },
  {
    name: "Midj",
    slug: "midj",
    category: "furniture",
    categoryLabel: "Furniture",
    image: "/media/partners/marks/midj.png",
    url: "https://www.midj.com",
  },
  {
    name: "Moooi",
    slug: "moooi",
    category: "furniture",
    categoryLabel: "Furniture",
    logo: "/media/partners/svg/moooi.svg",
    image: "/media/partners/marks/moooi.png",
    url: "https://www.moooi.com",
  },
  {
    name: "Victoria + Albert",
    slug: "victoria-albert",
    category: "bath",
    categoryLabel: "Bath & wellness",
    image: "/media/partners/marks/victoria-albert.png",
    url: "https://www.vandabaths.com",
  },
  {
    name: "Dorn Bracht",
    slug: "dorn-bracht",
    category: "bath",
    categoryLabel: "Bath & wellness",
    logo: "/media/partners/svg/dorn-bracht.svg",
    url: "https://www.dornbracht.com",
  },
  {
    name: "Cerasa",
    slug: "cerasa",
    category: "bath",
    categoryLabel: "Bath & wellness",
    image: "/media/partners/marks/cerasa.png",
    url: "https://www.cerasa.it",
  },
  {
    name: "Hansgrohe",
    slug: "hansgrohe",
    category: "bath",
    categoryLabel: "Bath & wellness",
    logo: "/media/partners/svg/hansgrohe.svg",
    image: "/media/partners/marks/hansgrohe.png",
    url: "https://www.hansgrohe.com",
  },
  {
    name: "THG Paris",
    slug: "thg-paris",
    category: "bath",
    categoryLabel: "Bath & wellness",
    image: "/media/partners/marks/thg-paris.png",
    url: "https://www.thg-paris.com",
  },
  {
    name: "Porcelanosa",
    slug: "porcelanosa",
    category: "bath",
    categoryLabel: "Bath & wellness",
    image: "/media/partners/marks/porcelanosa.png",
    url: "https://www.porcelanosa.com",
  },
  {
    name: "Cielo",
    slug: "cielo",
    category: "bath",
    categoryLabel: "Bath & wellness",
    image: "/media/partners/marks/cielo.png",
    url: "https://www.ceramicacielo.it",
  },
  {
    name: "Salvatori",
    slug: "salvatori",
    category: "bath",
    categoryLabel: "Bath & wellness",
    image: "/media/partners/marks/salvatori.png",
    url: "https://www.salvatori.it",
  },
  {
    name: "Varier",
    slug: "varier",
    category: "office",
    categoryLabel: "Office",
    image: "/media/partners/marks/varier.png",
    url: "https://www.varierfurniture.com",
  },
  {
    name: "Arredoufficio",
    slug: "arredoufficio",
    category: "office",
    categoryLabel: "Office",
    image: "/media/partners/marks/arredoufficio.png",
  },
  {
    name: "USM",
    slug: "usm",
    category: "office",
    categoryLabel: "Office",
    logo: "/media/partners/svg/usm.svg",
    url: "https://www.usm.com",
  },
  {
    name: "Bene",
    slug: "bene",
    category: "office",
    categoryLabel: "Office",
    logo: "/media/partners/svg/bene.svg",
    url: "https://www.bene.com",
  },
  {
    name: "Brokis",
    slug: "brokis",
    category: "lighting",
    categoryLabel: "Lighting",
    logo: "/media/partners/svg/brokis.svg",
    url: "https://www.brokis.cz",
  },
  {
    name: "Bomma",
    slug: "bomma",
    category: "lighting",
    categoryLabel: "Lighting",
    logo: "/media/partners/svg/bomma.svg",
    url: "https://www.bomma.cz",
  },
  {
    name: "Brand van Egmond",
    slug: "brand-van-egmond",
    category: "lighting",
    categoryLabel: "Lighting",
    image: "/media/partners/marks/brand-van-egmond.png",
    url: "https://www.brandvanegmond.com",
  },
  {
    name: "Northern Lighting",
    slug: "northern-lighting",
    category: "lighting",
    categoryLabel: "Lighting",
    image: "/media/partners/marks/northern-lighting.png",
    url: "https://northern.no",
  },
  {
    name: "Windfall",
    slug: "windfall",
    category: "lighting",
    categoryLabel: "Lighting",
    image: "/media/partners/marks/windfall.png",
    url: "https://www.windfall-gmbh.com",
  },
  {
    name: "Luci Italiane",
    slug: "luci-italiane",
    category: "lighting",
    categoryLabel: "Lighting",
    image: "/media/partners/marks/luci-italiane.png",
  },
  {
    name: "Terzani",
    slug: "terzani",
    category: "lighting",
    categoryLabel: "Lighting",
    image: "/media/partners/marks/terzani.png",
    url: "https://www.terzani.com",
  },
  {
    name: "Delightfull",
    slug: "delightfull",
    category: "lighting",
    categoryLabel: "Lighting",
    logo: "/media/partners/svg/delightfull.svg",
    url: "https://www.delightfull.eu",
  },
  {
    name: "Knikerboker",
    slug: "knikerboker",
    category: "lighting",
    categoryLabel: "Lighting",
    image: "/media/partners/marks/knikerboker.png",
    url: "https://www.knikerboker.it",
  },
  {
    name: "Innermost",
    slug: "innermost",
    category: "lighting",
    categoryLabel: "Lighting",
    image: "/media/partners/marks/innermost.png",
    url: "https://www.innermost.net",
  },
  {
    name: "Valerie Objects",
    slug: "valerie-objects",
    category: "lighting",
    categoryLabel: "Lighting",
    image: "/media/partners/marks/valerie-objects.png",
    url: "https://www.valerie-objects.com",
  },
  {
    name: "Bocci",
    slug: "bocci",
    category: "lighting",
    categoryLabel: "Lighting",
    image: "/media/partners/marks/bocci.png",
    url: "https://bocci.com",
  },
  {
    name: "Masiero",
    slug: "masiero",
    category: "lighting",
    categoryLabel: "Lighting",
    logo: "/media/partners/svg/masiero.svg",
    url: "https://www.masierogroup.com",
  },
  {
    name: "Porta Romana",
    slug: "porta-romana",
    category: "lighting",
    categoryLabel: "Lighting",
    logo: "/media/partners/svg/porta-romana.svg",
    url: "https://www.portaromana.com",
  },
  {
    name: "Zenza",
    slug: "zenza",
    category: "lighting",
    categoryLabel: "Lighting",
    image: "/media/partners/marks/zenza.png",
    url: "https://www.zenzahome.com",
  },
  {
    name: "Quasar",
    slug: "quasar",
    category: "lighting",
    categoryLabel: "Lighting",
    logo: "/media/partners/svg/quasar.svg",
    url: "https://www.quasar.nl",
  },
  {
    name: "Flos",
    slug: "flos",
    category: "lighting",
    categoryLabel: "Lighting",
    logo: "/media/partners/svg/flos.svg",
    image: "/media/partners/marks/flos.png",
    url: "https://www.flos.com",
  },
  {
    name: "Vibia",
    slug: "vibia",
    category: "lighting",
    categoryLabel: "Lighting",
    logo: "/media/partners/svg/vibia.svg",
    url: "https://www.vibia.com",
  },
  {
    name: "Pulpo",
    slug: "pulpo",
    category: "lighting",
    categoryLabel: "Lighting",
    image: "/media/partners/marks/pulpo.png",
    url: "https://www.pulpoproducts.com",
  },
  {
    name: "Northern",
    slug: "northern",
    category: "lighting",
    categoryLabel: "Lighting",
    image: "/media/partners/marks/northern.png",
    url: "https://northern.no",
  },
  {
    name: "Bover",
    slug: "bover",
    category: "lighting",
    categoryLabel: "Lighting",
    logo: "/media/partners/svg/bover.svg",
    url: "https://www.bover.es",
  },
  {
    name: "Kettal",
    slug: "kettal",
    category: "outdoor",
    categoryLabel: "Outdoor",
    image: "/media/partners/marks/kettal.png",
    url: "https://www.kettal.com",
  },
  {
    name: "Vondom",
    slug: "vondom",
    category: "outdoor",
    categoryLabel: "Outdoor",
    logo: "/media/partners/svg/vondom.svg",
    url: "https://www.vondom.com",
  },
  {
    name: "Emu",
    slug: "emu",
    category: "outdoor",
    categoryLabel: "Outdoor",
    image: "/media/partners/marks/emu.png",
    url: "https://www.emu.it",
  },
  {
    name: "Extremis",
    slug: "extremis",
    category: "outdoor",
    categoryLabel: "Outdoor",
    logo: "/media/partners/svg/extremis.svg",
    url: "https://www.extremis.com",
  },
  {
    name: "Royal Botania",
    slug: "royal-botania",
    category: "outdoor",
    categoryLabel: "Outdoor",
    image: "/media/partners/marks/royal-botania.png",
    url: "https://www.royalbotania.com",
  },
  {
    name: "Manutti",
    slug: "manutti",
    category: "outdoor",
    categoryLabel: "Outdoor",
    image: "/media/partners/marks/manutti.png",
    url: "https://www.manutti.com",
  },
  {
    name: "Cane Line",
    slug: "cane-line",
    category: "outdoor",
    categoryLabel: "Outdoor",
    image: "/media/partners/marks/cane-line.png",
    url: "https://www.cane-line.com",
  },
  {
    name: "Tribu",
    slug: "tribu",
    category: "outdoor",
    categoryLabel: "Outdoor",
    image: "/media/partners/marks/tribu.png",
    url: "https://www.tribu.com",
  },
  {
    name: "Expormim",
    slug: "expormim",
    category: "outdoor",
    categoryLabel: "Outdoor",
    image: "/media/partners/marks/expormim.png",
    url: "https://www.expormim.com",
  },
  {
    name: "Gloster",
    slug: "gloster",
    category: "outdoor",
    categoryLabel: "Outdoor",
    logo: "/media/partners/svg/gloster.svg",
    url: "https://www.gloster.com",
  },
  {
    name: "Roda",
    slug: "roda",
    category: "outdoor",
    categoryLabel: "Outdoor",
    logo: "/media/partners/svg/roda.svg",
    url: "https://www.rodaonline.com",
  },
  {
    name: "Varaschin",
    slug: "varaschin",
    category: "outdoor",
    categoryLabel: "Outdoor",
    image: "/media/partners/marks/varaschin.png",
    url: "https://www.varaschin.it",
  },
  {
    name: "Talenti",
    slug: "talenti",
    category: "outdoor",
    categoryLabel: "Outdoor",
    image: "/media/partners/marks/talenti.png",
    url: "https://www.talentispa.com",
  },
  {
    name: "Atmosphera",
    slug: "atmosphera",
    category: "outdoor",
    categoryLabel: "Outdoor",
    image: "/media/partners/marks/atmosphera.png",
    url: "https://www.atmosphera.com.it",
  },
  {
    name: "Ethimo",
    slug: "ethimo",
    category: "outdoor",
    categoryLabel: "Outdoor",
    image: "/media/partners/marks/ethimo.png",
    url: "https://www.ethimo.com",
  },
  {
    name: "Dedon",
    slug: "dedon",
    category: "outdoor",
    categoryLabel: "Outdoor",
    logo: "/media/partners/svg/dedon.svg",
    url: "https://www.dedon.de",
  },
  {
    name: "Zinc",
    slug: "zinc",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    logo: "/media/partners/svg/zinc.svg",
    url: "https://www.zinctextile.com",
  },
  {
    name: "Designers Guild",
    slug: "designers-guild",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    logo: "/media/partners/svg/designers-guild.svg",
    url: "https://www.designersguild.com",
  },
  {
    name: "Elite Decor",
    slug: "elite-decor",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    image: "/media/partners/marks/elite-decor.png",
  },
  {
    name: "Ontario Fabrics",
    slug: "ontario-fabrics",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    image: "/media/partners/marks/ontario-fabrics.png",
  },
  {
    name: "Pedroso & Os\u00f3rio",
    slug: "pedroso-os-rio",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    image: "/media/partners/marks/pedroso-os-rio.png",
  },
  {
    name: "Camengo",
    slug: "camengo",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    logo: "/media/partners/svg/camengo.svg",
    url: "https://www.camengo.com",
  },
  {
    name: "JAB",
    slug: "jab",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    image: "/media/partners/marks/jab.png",
    url: "https://www.jab.de",
  },
  {
    name: "Elitis",
    slug: "elitis",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    image: "/media/partners/marks/elitis.png",
    url: "https://www.elitis.fr",
  },
  {
    name: "Studio465",
    slug: "studio465",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    image: "/media/partners/marks/studio465.png",
  },
  {
    name: "Lee Jofa",
    slug: "lee-jofa",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    logo: "/media/partners/svg/lee-jofa.svg",
    url: "https://www.kravet.com/lee-jofa",
  },
  {
    name: "Sunbrella",
    slug: "sunbrella",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    logo: "/media/partners/svg/sunbrella.svg",
    url: "https://www.sunbrella.com",
  },
  {
    name: "James Malone",
    slug: "james-malone",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    image: "/media/partners/marks/james-malone.png",
    url: "https://www.james-malone.com",
  },
  {
    name: "Kobe",
    slug: "kobe",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    image: "/media/partners/marks/kobe.png",
    url: "https://www.kobefabrics.com",
  },
  {
    name: "Dedar",
    slug: "dedar",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    logo: "/media/partners/svg/dedar.svg",
    image: "/media/partners/marks/dedar.png",
    url: "https://www.dedar.com",
  },
  {
    name: "Javier Barrio",
    slug: "javier-barrio",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    image: "/media/partners/marks/javier-barrio.png",
  },
  {
    name: "Misia",
    slug: "misia",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    logo: "/media/partners/svg/misia.svg",
    url: "https://www.misia-paris.com",
  },
  {
    name: "Casamance",
    slug: "casamance",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    logo: "/media/partners/svg/casamance.svg",
    url: "https://www.casamance.com",
  },
  {
    name: "Villa Nova",
    slug: "villa-nova",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    image: "/media/partners/marks/villa-nova.png",
    url: "https://www.villanova.co.uk",
  },
  {
    name: "Omexco",
    slug: "omexco",
    category: "textiles",
    categoryLabel: "Textiles & wallcovering",
    logo: "/media/partners/svg/omexco.svg",
    url: "https://www.omexco.com",
  },
  {
    name: "Pedini",
    slug: "pedini",
    category: "kitchen",
    categoryLabel: "Kitchen",
    logo: "/media/partners/svg/pedini.svg",
    url: "https://www.pedini.it",
  },
  {
    name: "Bulthaup",
    slug: "bulthaup",
    category: "kitchen",
    categoryLabel: "Kitchen",
    logo: "/media/partners/svg/bulthaup.svg",
    url: "https://www.bulthaup.com",
  },
  {
    name: "Toncelli",
    slug: "toncelli",
    category: "kitchen",
    categoryLabel: "Kitchen",
    image: "/media/partners/marks/toncelli.png",
    url: "https://www.toncelli.it",
  },
  {
    name: "Binova",
    slug: "binova",
    category: "kitchen",
    categoryLabel: "Kitchen",
    image: "/media/partners/marks/binova.png",
    url: "https://www.binova.it",
  },
  {
    name: "Ferreira",
    slug: "ferreira",
    category: "accessories",
    categoryLabel: "Accessories",
    image: "/media/partners/marks/ferreira.png",
  },
  {
    name: "Baobab",
    slug: "baobab",
    category: "accessories",
    categoryLabel: "Accessories",
    image: "/media/partners/marks/baobab.png",
    url: "https://www.baobabcollection.com",
  },
  {
    name: "CC-Tapis",
    slug: "cc-tapis",
    category: "accessories",
    categoryLabel: "Accessories",
    image: "/media/partners/marks/cc-tapis.png",
    url: "https://www.cc-tapis.com",
  },
  {
    name: "PTMD",
    slug: "ptmd",
    category: "accessories",
    categoryLabel: "Accessories",
    image: "/media/partners/marks/ptmd.png",
    url: "https://www.ptmd.nl",
  },
  {
    name: "Giobagnara",
    slug: "giobagnara",
    category: "accessories",
    categoryLabel: "Accessories",
    image: "/media/partners/marks/giobagnara.png",
    url: "https://www.giobagnara.com",
  },
  {
    name: "Gert Snell",
    slug: "gert-snell",
    category: "accessories",
    categoryLabel: "Accessories",
    image: "/media/partners/marks/gert-snell.png",
  },
  {
    name: "Dome Dec",
    slug: "dome-dec",
    category: "accessories",
    categoryLabel: "Accessories",
    image: "/media/partners/marks/dome-dec.png",
    url: "https://www.domedeco.com",
  },
  {
    name: "Bazar Bizar",
    slug: "bazarbizar",
    category: "accessories",
    categoryLabel: "Accessories",
    image: "/media/partners/marks/bazarbizar.png",
    url: "https://www.bazarbizar.com",
  },
  {
    name: "Onno",
    slug: "onno",
    category: "accessories",
    categoryLabel: "Accessories",
    image: "/media/partners/marks/onno.png",
    url: "https://www.onnocollection.com",
  },
  {
    name: "Cotiling",
    slug: "cotiling",
    category: "accessories",
    categoryLabel: "Accessories",
    image: "/media/partners/marks/cotiling.png",
  },
  {
    name: "Serge Lesage",
    slug: "serge-lesage",
    category: "accessories",
    categoryLabel: "Accessories",
    image: "/media/partners/marks/serge-lesage.png",
    url: "https://www.sergelesage.com",
  }
];

export const partnerMarquee = partners.filter((_, i) => i % 2 === 0);

export function partnersGrouped() {
  return partnerCategories
    .map((category) => ({
      ...category,
      partners: partners.filter((partner) => partner.category === category.id),
    }))
    .filter((group) => group.partners.length > 0);
}
